export const BROADENBOUNDS = "BROADENBOUNDS";

export const SETBOUNDS = "SETBOUNDS";

export const SETMAPDATA = "SETMAPDATA";

export const SETBOUNDSATTRACTIONS = "SETBOUNDSATTRACTIONS";

export const SETVIEWPORTATTRACTIONS = "SETVIEWPORTATTRACTIONS";

export const SETSHOWDETAILSMODAL = "SETSHOWDETAILSMODAL";
