export const SETATTRACTIONSDETAILS = "SETATTRACTIONSDETAILS";

export const SETCOMMENTMODAL = "SETCOMMENTMODAL";

export const SETCOMMENTCONTENT = "SETCOMMENTCONTENT";

export const SETDELETEMODAL = "SETDELETEMODAL";
