export const SETATTRACTIONSDETAILS = "SETATTRACTIONSDETAILS";

export const SETCOMMENTMODAL = "SETCOMMENTMODAL";

export const SETCOMMENTCONTENT = "SETCOMMENTCONTENT";

export const SETDELETEMODAL = "SETDELETEMODAL";

export const SETEDITCOMMENT = "SETEDITCOMMENT";

export const SETATTRACTIONUSERSDATA = "SETATTRACTIONUSERSDATA";

export const SETATTRACTIONMAINDATA = "SETATTRACTIONMAINDATA";

export const SETLOADINGDATA = "SETLOADINGDATA";
